### PR TITLE
fix-stucked-bundle-in-uploading-state

### LINKED ISSUE #1875: Jobs stuck at uploading stage when user doesn't have enough disk space left
Screenshot from 2019-12-25 06-48-37

Jobs can't end when user don't have enough disk space left, the worker should fail the job

### PR DESCRIPTION
**Pull request by candicegjing**
Fixed #1875 and #1829 
During investigating on #1875, there are two issues were discovered:
1. `AttributeError: 'str' object has no attribute 'decode'`: might be related to #1853 
```
Traceback (most recent call last):
  File "/usr/local/bin/cl", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/opt/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 839, in do_command
    structured_result = command_fn()
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 833, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1229, in do_upload_command
    progress_callback=progress.update,
  File "/opt/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    error_body = e.read().decode()
AttributeError: 'str' object has no attribute 'decode'
```
2. Bundle failed to move to `failed` state for a very long time. It kept moving from `failed` --> `running` --> `failed` and caused the situation described in #1875. This is due to a very large retry number defined at [COMMAND_RETRY_SECONDS](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker.py#L35). When the current bundle failed from uploading, it keeps retrying until the number of retries becomes a negative value, see logic here [execute_bundle_service_command_with_retry](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker.py#L530). Hence, the bundle got stuck in uploading state will eventually move to a permanent `failed` state. However, this will take a very long time. 
**We need to decide how many times of retries should be used for function** `execute_bundle_service_command_with_retry` **as the existing value seems to be quite big.**

### CODE REVIEW

File: codalab/worker/bundle_service_client.py [hunk 1]
```diff
@@ -22,27 +22,20 @@ def wrapper(*args, **kwargs):
...
+                    e.seek(0)
+                    client_error = e.read()
+                    if e.reason == 'invalid_grant':
                         raise BundleAuthException(
-                            message
-                            + ': '
-                            + http.client.responses[e.code]
-                            + ' - '
-                            + json.dumps(client_error),
+                            message + ': ' + http.client.responses[e.code] + ' - ' + client_error,
```
Comment (percyliang) [inline codalab/worker/bundle_service_client.py:28]: Why is `json.dumps` gone now?

Comment (candicegjing) [reply codalab/worker/bundle_service_client.py:28]: 1. In the original logic [e.read().decode()](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/bundle_service_client.py#L25), `e.read()` was treated as a bytes object that can be decoded. However, in Python3, `e.read()` actually returns a string object which doesn't have `decode()` function. This is where the error `AttributeError: 'str' object has no attribute 'decode'` was coming from. So I removed the `decode()` method.
2. Since `e.read()` will return a plain string in Python3 now, the structure of parsing object `urllib.error.HTTPError` changed quite a lot comparing with the original way. The original `client_error` will return something similar to ```{
    "error": "bad client",
    "msg": "error message"
}```
However, right now, `e.read()` will directly return the error message as a Unicode string. I think it might not be necessary to convert it back and forth between a json object and string. (But I am open to discuss this, as one benefit of `json.dumps` is that it can ensure all the characters are ASCII encoded.)

File: codalab/worker/bundle_service_client.py [hunk 2]
```diff
@@ -22,27 +22,20 @@ def wrapper(*args, **kwargs):
                 raise BundleServiceException(message + ': ' + str(e), e.client_error)
             except urllib.error.HTTPError as e:
                 try:
-                    client_error = json.loads(e.read().decode())
-
-                    if client_error['error'] == 'invalid_grant':
+                    # Sets the file's current position at the offset 0. Otherwise, e.read() will return an empty string.
+                    e.seek(0)
```
Comment (percyliang) [inline codalab/worker/bundle_service_client.py]: This part is a bit strange...the offset is not always at 0?

**Review by percyliang — APPROVED** [review]

File: codalab/worker/bundle_service_client.py (hunk 2 above)
Comment (candicegjing) [reply codalab/worker/bundle_service_client.py]: There are two options:
1. Use `e.read()` but with `seek(0)` right before `e.read()`. Otherwise, `e.read()` will return an empty string from my experiments. 
2. Use `e.getvalue()`. This will directly return the real error message. It's one method belongs to `StringIO`, see [io.StringIO.getvalue](https://docs.python.org/3/library/io.html#io.StringIO.getvalue)
They are essentially the same. Open to change this, as I also feel it's quite strange in doing this.

**Comment by candicegjing** [comment]
@percyliang We also need to decide whether we want to keep the value of [COMMAND_RETRY_SECONDS](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker.py#L35), as it's actually using as a counter instead of seconds in retrying the command and it makes the jobs stuck in `running` state for a very long time.

File: codalab/worker/bundle_service_client.py (hunk 2 above)
Comment (percyliang) [reply codalab/worker/bundle_service_client.py]: `e.getvalue()` seems much more principled / simpler than having to `seek` and `read`, so I'd go with that if possible.

**Comment by percyliang** [comment]
@candicegjing Can you say more about `COMMAND_RETRY_SECONDS` (sounds like it's mis-named), what it's set to, and what behavior that causes, as well as what you think we should set it to?

**Comment by candicegjing** [comment]
> @candicegjing Can you say more about `COMMAND_RETRY_SECONDS` (sounds like it's mis-named), what it's set to, and what behavior that causes, as well as what you think we should set it to?

Oh, I put more detailed information in [the original PR comments](https://github.com/codalab/codalab-worksheets/pull/1884#issue-359750668). Basically, `COMMAND_RETRY_SECONDS` is using as a counter to track the number of retries when a bundle service client command failed at [execute_bundle_service_command_with_retry](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker.py#L527). I think normally a few times (e.g. 3 to 10 times) should be enough. I have updated the value to be `10`. But if I missed any background information, please let me know.

**Review by percyliang — COMMENTED** [review]
I think the reason we wanted a very long (perhaps infinite) wait time is to handle the case where the worker goes offline (maybe the server goes down for upgrade) - perhaps for days, and we want the worker to patiently wait until the connection is re-established.  This should probably be documented, and maybe there should be an exponential backoff.

File: codalab/worker/bundle_service_client.py (hunk 2 above)
Comment (candicegjing) [reply codalab/worker/bundle_service_client.py]: Actually, I just realized that I was wrong on this. `e.read()` without `e.seek(0)` should be the right way to handle it. The file pointer will originally be set at 0 when running `e.read()`, but will be changed after `e.read()` get executed. When I was testing, I tried to print out the logging information by calling `e.read()` once, then assigned the value to `client_error`, so the pointer changed its position.

Comment (percyliang) [reply codalab/worker/bundle_service_client.py]: If we do `x = e.read()` once, we can just use `x` and not depend on the cursor position or `e` for the error message, right?

**Comment by candicegjing** [comment]
> I think the reason we wanted a very long (perhaps infinite) wait time is to handle the case where the worker goes offline (maybe the server goes down for upgrade) - perhaps for days, and we want the worker to patiently wait until the connection is re-established. This should probably be documented, and maybe there should be an exponential backoff.

Yes. I agree with that case. #1875 happens when users' disk quota is full. Maybe I'll add a comment, update the variable naming and keep the value as the same as before for now, as either way the variable name isn't reflecting what it actually does in code logic?

File: codalab/worker/bundle_service_client.py (hunk 2 above)
Comment (candicegjing) [reply codalab/worker/bundle_service_client.py]: Yes, that's right. I have updated the code to use the standard `e.read()` in both files that have issues related to this.
