### PR TITLE
Fix modal position and font size

### LINKED ISSUE #1652: keyboard shortcuts css broken
image

### PR DESCRIPTION
**Pull request by epicfaace**
Fixes some regressions introduced by #1603, by increasing the base font size
and fixing the look and feel of the keyboard shortcuts modal (fixes #1652).

### CODE REVIEW

File: frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss [hunk 1]
```diff
@@ -31,4 +31,10 @@
     padding: 5px 6px 8px 6px;
     border-color: #eee;
     border-bottom: 1px solid #eee;
-  }
\ No newline at end of file
+  }
+#glossaryModal {
```
Comment (yipenghe) [inline frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss:35]: The position looks weird...also the shortcut '?' is broken saying
`TypeError: jquery__WEBPACK_IMPORTED_MODULE_8___default(...)(...).modal is not a function
`
Screenshot from 2019-11-13 10-07-56

**Review by yipenghe — CHANGES_REQUESTED** [review]

File: frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss (hunk 1 above)
Comment (epicfaace) [reply frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss:35]: The position should be working fine. You should edit `index.js` so that it live reloads the css from `overrides.scss`.

Comment (epicfaace) [reply frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss:35]: The jquery modal is another issue present on the `frontend` branch too. Making another issue for it.

Comment (yipenghe) [reply frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.scss:35]: I see you created the issue, I will update more info there & approve this

**Review by yipenghe — APPROVED** [review]
